os:
  - linux
  - osx
language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: PACKAGE=spotify-cli bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02
